### ISSUE TITLE
交互建议

### ISSUE THREAD

**Issue by aptx4869yuyang2017** [Moonvy/OpenPromptStudio#11]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/25080317/230870310-1f79fe2f-b4b8-49ac-badf-09c60fd7c870.png">

最好 字典和编辑区不重叠，因为有同时操作的场景

**Comment by yArna** [comment]
嗯，不过有时我只想找到词后点击加入，不用看编辑区，考虑可以做成可拖拽调整尺寸的，这样适用性高些，不行重叠可以自己调整词典宽度
