### ISSUE TITLE
/src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts存在一个错误

### ISSUE THREAD

**Issue by GlowingBrick** [Moonvy/OpenPromptStudio#24]
/src/Compoents/PromptEditor/Lib/parsePrompts/parsers/Midjourney/index.ts 这个文件，第一行 
`import { IPromptWord, PromptWordType } from "../../ParsePrompts" `
存在错误，应该改成
`import { IPromptWord, PromptWordType } from "../../parsePrompts"`
由于windows环境不分大小写，所以应该可以正常运行，但是linux环境则会报错。

**Comment by yArna** [comment]
fix by #25
