### ISSUE TITLE
Notion连接错误:没有Notion数据库的访问权限.请在此Notion数据库页面菜单的'Connections'中添加你的集成应用

### ISSUE THREAD

**Issue by Yanick112** [Moonvy/OpenPromptStudio#39]
Notion连接错误:没有Notion数据库的访问权限.请在此Notion数据库页面菜单的'Connections'中添加你的集成应用，咋整呀

**Comment by Yanick112** [comment]
已经在connections里添加了

**Comment by xiguagaga** [comment]
我也有这个问题，有时候可以连接上，但大多数时候提示这个错误

**Comment by xiguagaga** [comment]
我解决了这个问题

请注意看文档中获取Database ID的方式。
![image](https://user-images.githubusercontent.com/31040713/232272400-63dbd446-7807-4a36-bd99-2cbbab800422.png)

**Comment by Yanick112** [comment]
还是存在这个问题，已经按照说明里的在设置了，这个是我自己新建的数据库，可能是某处没设置好，但实在找不到了




***@***.***
 
发件人： 西瓜是个好西瓜
发送时间： 2023-04-16 13:15
收件人： Moonvy/OpenPromptStudio
抄送： Yanick112; Author
主题： Re: [Moonvy/OpenPromptStudio] Notion连接错误:没有Notion数据库的访问权限.请在此Notion数据库页面菜单的'Connections'中添加你的集成应用 (Issue #39)
我解决了这个问题
请注意看文档中获取Database ID的方式。

**Comment by ArryArry** [comment]
![image](https://user-images.githubusercontent.com/37373910/232556421-8a2a7027-a6a3-4fbc-9199-1d8b214bf8df.png)

**Comment by QiuQiubaby0302** [comment]
> 我解决了这个问题
> 
> 请注意看文档中获取Database ID的方式。 ![image](https://user-images.githubusercontent.com/31040713/232272400-63dbd446-7807-4a36-bd99-2cbbab800422.png)

我还是没解决这个问题，同样的方法，我用复制过来的演示文档就可以，但是导入的CSV就不行，在导入部分，如果是普通CSV可以链接，但是生成的是乱码，UTF-8的CSV，不乱码，但是链接不上。无解了。。。。

**Comment by realyn** [comment]
> > 我解决了这个问题
> > 请注意看文档中获取Database ID的方式。 ![image](https://user-images.githubusercontent.com/31040713/232272400-63dbd446-7807-4a36-bd99-2cbbab800422.png)
> 
> 我还是没解决这个问题，同样的方法，我用复制过来的演示文档就可以，但是导入的CSV就不行，在导入部分，如果是普通CSV可以链接，但是生成的是乱码，UTF-8的CSV，不乱码，但是链接不上。无解了。。。。

只拷id，前面域名及后面的参数都删掉，然后粘进去

**Comment by jasontusi** [comment]
每次打开都需要连接一次notion吗

**Comment by pukegjf** [comment]
谢谢

**Comment by vxinhao** [comment]
> > > 我解决了这个问题
> > > 请注意看文档中获取Database ID的方式。 ![image](https://user-images.githubusercontent.com/31040713/232272400-63dbd446-7807-4a36-bd99-2cbbab800422.png)
> > 
> > 
> > 我还是没解决这个问题，同样的方法，我用复制过来的演示文档就可以，但是导入的CSV就不行，在导入部分，如果是普通CSV可以链接，但是生成的是乱码，UTF-8的CSV，不乱码，但是链接不上。无解了。。。。
> 
> 只拷id，前面域名及后面的参数都删掉，然后粘进去

3Q，可算是解决了
这个是正解。

**Comment by preppy593** [comment]
![123](https://github.com/Moonvy/OpenPromptStudio/assets/52643526/8bef9750-8d25-414c-a786-a9ab641199cd)

请问我已经把ID单独复制出来了为什么还是提示同样的报错呢？

**Comment by zwwaxx** [comment]
没用的  都试了 没办法

**Comment by yArna** [comment]
cors 服务国内访问好像有问题，换了个服务器，现在可以了

**Comment by renniaofei** [comment]
> cors 服务国内访问好像有问题，换了个服务器，现在可以了

我发现也是这个问题，后天全局模式就可以了。
