### ISSUE TITLE
数据库连接错误

### ISSUE THREAD

**Issue by Arli404** [Moonvy/OpenPromptStudio#4]
一直提示,Notion连接错误:没有Notion数据库的访问权限。请在此Notion 数据库页面菜单的'Connections'中添加你的集成应用
但是已经反复确认Token和数据库的BaseID无误,token的访问权限也已经连接至数据库和上级页面,但还是出错0.0

**Comment by luoq24** [comment]
很不幸，我也遇到了同样的问题。
网页错误提示：
Notion 连接错误：APIResponseError: Could not find database with ID: 7a4c9745-3e32-4117-bb6d-a9722465487d. Make sure the relevant pages and databases are shared with your integration.

**Comment by luoq24** [comment]
> 

额，我连上了。
不100%确定，但猜测是这样：
按照教程，执行“在 Notion 数据库连接集成插件”，此操作成功后，Connections菜单处会显示你的插件名和图标
立即在OPS网页，执行“载入”

**Comment by yArna** [comment]
是不是没做这一步
![image](https://user-images.githubusercontent.com/82231420/230758675-d4b09d4a-177c-4e52-ab5c-50820e7aa66c.png)

**Comment by Arli404** [comment]
非常感谢,已经OK了,我之前使用了自建的数据库,现在重新复制了模板,再基于模板修改,就没问题了
