### ISSUE TITLE
docker中翻译功能未生效

### ISSUE THREAD

**Issue by wekingchen** [Moonvy/OpenPromptStudio#64]
自行构建镜像后，在运行容器中加入了腾讯翻译的配置：
TENCENT_SECRET_ID="AKIDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
TENCENT_SECRET_KEY="a5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

但是启动后，翻译功能并没有生效，输入文字时并不会自动翻译，能查查原因吗？

**Comment by wekingchen** [comment]
不知道怎么看容器的log，但是在腾讯云的控制台并没有看到任何调用记录，应该说明在容器中没有使用到翻译功能吧？

**Comment by yArna** [comment]
可以用 `docker logs  CONTAINER` 看容器输出

我想你是不是需要配置：`LOCAL_TRANSLATE_HOST`
像是这样，告诉 Web 端该如何访问翻译服务：
`LOCAL_TRANSLATE_HOST="192.168.50.222:3000"`

**Comment by wekingchen** [comment]
感谢回复，我把39011端口反代到域名，然后用LOCAL_TRANSLATE_HOST参数定义到域名，就可以翻译了~
