### ISSUE TITLE
你好，请问项目中19212端口是做什么用的？

### ISSUE THREAD

**Issue by doraemon0711** [Moonvy/OpenPromptStudio#70]
我在本地通过docker部署项目后，添加了腾讯翻译的令牌之后翻译仍然不生效，后来查看wiki里的说明有两个端口19212和39011

这两个端口是否都是翻译服务的端口，只是一开始使用的是19212后来改成了39011？

[wiki的说明](https://github.com/Moonvy/OpenPromptStudio/tree/master/docker#%E8%BF%90%E8%A1%8C%E5%AE%B9%E5%99%A8)
<img width="700" alt="image" src="https://user-images.githubusercontent.com/13547208/235688032-cde08e1c-7363-4a3e-9fff-f187be01d9a7.png">

源码中两个接口都有在用
<img width="583" alt="image" src="https://user-images.githubusercontent.com/13547208/235688318-44d89557-3e80-4d74-80fb-46616b0217cf.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/13547208/235688431-b32c9381-aba2-4854-9e30-010a6d4ee94e.png">

**Comment by yArna** [comment]
是的，这是个错误，最新版本里修复了
